### ISSUE TITLE
Type 'Data' is not assignable to type 'From'.

### ISSUE THREAD

**Issue by CharlZKP** [jpcx/ts-ev#1]
Got this problem 
while trying to compile 

A type predicate's type must be assignable to its parameter's type.
  Type 'Data' is not assignable to type 'From'.
    'Data' is assignable to the constraint of type 'From', but 'From' could be instantiated with a different subtype of constraint 'any[]'.ts(2677)

My node version is v16.13.2

![image](https://user-images.githubusercontent.com/11996083/151737300-daf58f55-1f64-4ea2-9b7f-bf58a9165c4e.png)

**Comment by jpcx** [comment]
Hello, thank you for the report and sorry I missed this! I've fixed the bug and updated the dependencies; you should be able to install 0.4.0 from NPM now.
